vich_uploader:
  db_driver: orm

  mappings:
    attachments:
      uri_prefix: /uploads/attachments
      upload_destination: '%kernel.project_dir%/public/uploads/attachments'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      directory_namer:
        service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
        options:
          date_time_format: 'Y'
          date_time_property: createdAt
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    avatars:
      uri_prefix: /uploads/avatars
      upload_destination: '%kernel.project_dir%/public/uploads/avatars'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      directory_namer:
        service: App\Core\UploaderBundle\PropertyGroupedDirectoryNamer
        options:
          property: id
          modulo: 10000
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
